import { BLRZone, Product, Order } from './types';
import { PRODUCTS } from '@/data/products';

export const BLR_ZONES: BLRZone[] = [
  {
    id: 'hsr-layout',
    name: 'HSR Layout',
    area: 'Sectors 1 to 7',
    pincode: '560102',
    hubDistanceKm: 2.1,
    deliveryEtaMinutes: 25,
    porterBikeFee: 49,
    expressDispatchFee: 79,
    popularTechHub: 'Near 27th Main / Startups Hub',
  },
  {
    id: 'koramangala',
    name: 'Koramangala',
    area: 'Blocks 1 to 8 & ST Bed',
    pincode: '560034',
    hubDistanceKm: 3.4,
    deliveryEtaMinutes: 30,
    porterBikeFee: 49,
    expressDispatchFee: 79,
    popularTechHub: 'Sony World Junction / Jyoti Nivas',
  },
  {
    id: 'indiranagar',
    name: 'Indiranagar',
    area: '100ft Rd & CMH Rd',
    pincode: '560038',
    hubDistanceKm: 5.8,
    deliveryEtaMinutes: 35,
    porterBikeFee: 59,
    expressDispatchFee: 89,
    popularTechHub: 'Defense Colony / Metro Station',
  },
  {
    id: 'bellandur',
    name: 'Bellandur & ORR',
    area: 'Outer Ring Road & Ecospace',
    pincode: '560103',
    hubDistanceKm: 6.2,
    deliveryEtaMinutes: 38,
    porterBikeFee: 59,
    expressDispatchFee: 89,
    popularTechHub: 'EcoWorld / Prestige Tech Park',
  },
  {
    id: 'whitefield',
    name: 'Whitefield',
    area: 'ITPL & EPIP Zone',
    pincode: '560066',
    hubDistanceKm: 14.5,
    deliveryEtaMinutes: 48,
    porterBikeFee: 79,
    expressDispatchFee: 119,
    popularTechHub: 'ITPL / Hoodi / Kundalahalli',
  },
  {
    id: 'electronic-city',
    name: 'Electronic City',
    area: 'Phase 1 & Phase 2',
    pincode: '560100',
    hubDistanceKm: 12.0,
    deliveryEtaMinutes: 45,
    porterBikeFee: 69,
    expressDispatchFee: 99,
    popularTechHub: 'Infosys Campus / NeoTown',
  },
  {
    id: 'jp-nagar',
    name: 'JP Nagar & Jayanagar',
    area: 'Phases 1 to 7',
    pincode: '560078',
    hubDistanceKm: 7.5,
    deliveryEtaMinutes: 40,
    porterBikeFee: 59,
    expressDispatchFee: 89,
    popularTechHub: 'Sarakki / Vega City Mall',
  },
  {
    id: 'malleshwaram',
    name: 'Malleshwaram & Rajajinagar',
    area: 'Margosa & Sampige Road',
    pincode: '560003',
    hubDistanceKm: 13.2,
    deliveryEtaMinutes: 50,
    porterBikeFee: 75,
    expressDispatchFee: 109,
    popularTechHub: 'IISc Campus / Orion Mall Area',
  },
  {
    id: 'peenya',
    name: 'Peenya Industrial Area',
    area: 'Peenya Phases 1-4',
    pincode: '560058',
    hubDistanceKm: 18.0,
    deliveryEtaMinutes: 55,
    porterBikeFee: 89,
    expressDispatchFee: 129,
    popularTechHub: 'Peenya Metro / Manufacturing Cluster',
  },
];

export const INITIAL_PRODUCTS: Product[] = PRODUCTS;

export const INITIAL_ORDERS: Order[] = [];

